// Mock data for when database connection is unavailable
// export const mockBooks = [
//   {
//     id: 1,
//     title: "The Brothers Karamazov",
//     author: "Fyodor Dostoevsky",
//     description:
//       "A passionate philosophical novel set in 19th-century Russia, which explores ethical debates of God, free will, and morality.",
//     image_url: "/images/books/brothers-karamazov.jpg",
//     genre: "Literary Fiction",
//     created_at: new Date().toISOString(),
//     updated_at: new Date().toISOString(),
//   },
//   {
//     id: 2,
//     title: "East of Eden",
//     author: "John Steinbeck",
//     description:
//       "A multigenerational family saga set in the Salinas Valley, California, exploring themes of good and evil through the intertwined stories of two families.",
//     image_url: "/images/books/east-of-eden.jpg",
//     genre: "Literary Fiction",
//     created_at: new Date().toISOString(),
//     updated_at: new Date().toISOString(),
//   },
//   {
//     id: 3,
//     title: "The Fifth Season",
//     author: "N.K. Jemisin",
//     description:
//       "Set in a world where catastrophic climate change occurs regularly, this novel follows a woman searching for her daughter while navigating a society divided by powers.",
//     image_url: "/images/books/fifth-season.jpg",
//     genre: "Science Fiction & Fantasy",
//     created_at: new Date().toISOString(),
//     updated_at: new Date().toISOString(),
//   },
//   {
//     id: 4,
//     title: "Jane Eyre",
//     author: "Charlotte Brontë",
//     description:
//       "A novel about a strong-willed orphan who becomes a governess, falls in love with her employer, and discovers his dark secret.",
//     image_url: "/images/books/jane-eyre.jpg",
//     genre: "Literary Fiction",
//     created_at: new Date().toISOString(),
//     updated_at: new Date().toISOString(),
//   },
//   {
//     id: 5,
//     title: "Anna Karenina",
//     author: "Leo Tolstoy",
//     description:
//       "A complex novel of family life among the Russian aristocracy, focusing on an adulterous affair between Anna Karenina and Count Vronsky.",
//     image_url: "/images/books/anna-karenina.jpg",
//     genre: "Literary Fiction",
//     created_at: new Date().toISOString(),
//     updated_at: new Date().toISOString(),
//   },
//   {
//     id: 6,
//     title: "Giovanni's Room",
//     author: "James Baldwin",
//     description:
//       "A groundbreaking novel that follows an American man living in Paris as he grapples with his sexual identity and relationships.",
//     image_url: "/images/books/giovannis-room.jpg",
//     genre: "Historical Fiction",
//     created_at: new Date().toISOString(),
//     updated_at: new Date().toISOString(),
//   },
//   {
//     id: 7,
//     title: "My Brilliant Friend",
//     author: "Elena Ferrante",
//     description:
//       "The first novel in the Neapolitan quartet that traces the friendship between Elena and Lila, from their childhood in a poor Naples neighborhood through their diverging paths in life.",
//     image_url: "/images/books/my-brilliant-friend.jpg",
//     genre: "Literary Fiction",
//     created_at: new Date().toISOString(),
//     updated_at: new Date().toISOString(),
//   },
//   {
//     id: 8,
//     title: "The Remains of the Day",
//     author: "Kazuo Ishiguro",
//     description:
//       "The story of an English butler reflecting on his life of service and missed opportunities as he takes a road trip through the countryside.",
//     image_url: "/images/books/remains-of-the-day.jpg",
//     genre: "Historical Fiction",
//     created_at: new Date().toISOString(),
//     updated_at: new Date().toISOString(),
//   },
//   {
//     id: 9,
//     title: "The Left Hand of Darkness",
//     author: "Ursula K. Le Guin",
//     description:
//       "A science fiction novel that follows an envoy sent to convince the ambisexual people of the planet Gethen to join an interplanetary collective.",
//     image_url: "/images/books/left-hand-of-darkness.jpg",
//     genre: "Science Fiction & Fantasy",
//     created_at: new Date().toISOString(),
//     updated_at: new Date().toISOString(),
//   },
// ];


export const mockBooks = [
  {
    id: 1,
    title: "Clean Code: A Handbook of Agile Software Craftsmanship",
    author: "Robert C. Martin",
    description: "A must-read for every programmer, this book teaches principles and best practices of writing clean, maintainable, and efficient code.",
    image_url: "/images/books/clean-code.jpg",
    genre: "Software Engineering",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: "You Don’t Know JS: Up & Going",
    author: "Kyle Simpson",
    description: "The first book in the ‘You Don’t Know JS’ series introduces core concepts of JavaScript for beginners and experienced developers alike.",
    image_url: "/images/books/clean-code.jpg",
    // image_url: "/images/books/ydkjs-up-going.jpg",
    genre: "Programming Languages",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    description: "A classic book introducing 23 design patterns, providing an essential reference for architecting scalable and maintainable code.",
    image_url: "/images/books/clean-code.jpg",
    // image_url: "/images/books/design-patterns.jpg",
    genre: "Software Architecture",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    title: "Introduction to the Theory of Computation",
    author: "Michael Sipser",
    description: "A foundational text for computer science students, covering automata theory, formal languages, and computational complexity.",
    image_url: "/images/books/clean-code.jpg",
    // image_url: "/images/books/theory-of-computation.jpg",
    genre: "Computer Science Theory",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    title: "Refactoring: Improving the Design of Existing Code",
    author: "Martin Fowler",
    description: "A guide to refactoring techniques and strategies that help programmers improve code readability, structure, and efficiency.",
    image_url: "/images/books/clean-code.jpg",
    // image_url: "/images/books/refactoring.jpg",
    genre: "Software Engineering",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    title: "The Pragmatic Programmer: Your Journey to Mastery",
    author: "Andrew Hunt, David Thomas",
    description: "A classic programming book packed with practical advice and tips for software developers looking to level up their craft.",
    image_url: "/images/books/clean-code.jpg",
    // image_url: "/images/books/pragmatic-programmer.jpg",
    genre: "Software Engineering",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 7,
    title: "Structure and Interpretation of Computer Programs",
    author: "Harold Abelson, Gerald Jay Sussman",
    description: "A legendary text in computer science education, combining theory and functional programming with Scheme.",
    image_url: "/images/books/clean-code.jpg",
    // image_url: "/images/books/sicp.jpg",
    genre: "Programming Languages",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 8,
    title: "Effective Java",
    author: "Joshua Bloch",
    description: "Essential best practices for writing robust Java code, illustrated through practical tips and code examples.",
    image_url: "/images/books/clean-code.jpg",
    // image_url: "/images/books/effective-java.jpg",
    genre: "Programming Languages",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 9,
    title: "Algorithms",
    author: "Robert Sedgewick, Kevin Wayne",
    description: "Comprehensive coverage of key algorithms and data structures, supplemented with implementations in Java.",
    image_url: "/images/books/clean-code.jpg",
    // image_url: "/images/books/algorithms.jpg",
    genre: "Computer Science Theory",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];
